# Generated by Django 5.2.5 on 2025-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cultural_background',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='religious_affiliation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='spiritual_beliefs',
            field=models.CharField(blank=True, help_text='Spiritual beliefs or practices', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='traditional_names',
            field=models.CharField(blank=True, help_text='Traditional/clan names', max_length=200),
        ),
    ]
