# Generated by Django 5.2.5 on 2025-10-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_profile_is_active_profile_is_deceased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_active',
        ),
    ]
