# Generated by Django 5.2.5 on 2025-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_remove_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
