# Generated by Django 4.2.1 on 2023-08-06 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0005_post_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_approved',
            new_name='approved',
        ),
    ]
