# Generated by Django 4.2.1 on 2023-08-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0014_alter_reply_options_group_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_image'),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
