# Generated by Django 4.0.1 on 2023-10-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin',
            new_name='profile',
        ),
    ]
