# Generated by Django 4.0.1 on 2023-11-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0003_remove_group_deceased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='chema.group'),
        ),
        migrations.AlterField(
            model_name='dependent',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
