# Generated by Django 5.2.5 on 2025-09-29 19:17

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Funeral Expenses Support', max_length=200)),
                ('description', models.TextField(help_text='Explain what the contributions will be used for')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))])),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='ZAR', help_text='Currency code (ZAR, USD, etc.)', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('closed', 'Closed')], default='active', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, help_text='Optional deadline for contributions', null=True)),
                ('funeral_date', models.DateTimeField(blank=True, help_text='Date of funeral service', null=True)),
                ('expense_breakdown', models.JSONField(blank=True, default=dict, help_text='Breakdown of expected expenses')),
                ('public_updates', models.BooleanField(default=True, help_text='Allow contributors to see updates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_campaign', to='group.group')),
                ('memorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_campaign', to='feeds.memorial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contributor_name', models.CharField(blank=True, help_text='Name for anonymous contributors', max_length=200)),
                ('contributor_email', models.EmailField(blank=True, max_length=254)),
                ('contributor_phone', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('ecocash', 'EcoCash'), ('airtel_money', 'Airtel Money'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Credit/Debit Card'), ('cash', 'Cash (Offline)'), ('other', 'Other')], default='mpesa', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External payment system transaction ID', max_length=100)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message to the family')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('relationship_to_deceased', models.CharField(blank=True, help_text='Friend, Colleague, Family, etc.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributions.contributioncampaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('progress', 'Progress Update'), ('expense', 'Expense Report'), ('milestone', 'Milestone Reached'), ('thank_you', 'Thank You Message'), ('urgent', 'Urgent Need'), ('completion', 'Campaign Complete')], default='progress', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='contribution_updates/')),
                ('notify_contributors', models.BooleanField(default=True, help_text='Send notifications to all contributors')),
                ('is_public', models.BooleanField(default=True, help_text='Visible to all group members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='contributions.contributioncampaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('coffin', 'Coffin/Casket'), ('transport', 'Transportation'), ('venue', 'Venue Costs'), ('catering', 'Food & Catering'), ('flowers', 'Flowers & Decorations'), ('printing', 'Programs & Printing'), ('legal', 'Legal/Documentation'), ('accommodation', 'Accommodation'), ('other', 'Other Expenses')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='ZAR', max_length=3)),
                ('receipt_image', models.ImageField(blank=True, upload_to='expense_receipts/')),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('date_incurred', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='contributions.contributioncampaign')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_incurred', '-created_at'],
            },
        ),
    ]
