# Generated by Django 5.2.5 on 2025-10-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributioncampaign',
            name='memorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_campaign', to='memorial.memorial'),
        ),
    ]
