# Generated by Django 5.2.5 on 2025-10-11 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_alter_contributioncampaign_memorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributioncampaign',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='contributioncampaign',
            name='expense_breakdown',
        ),
    ]
