# Generated by Django 5.2.5 on 2025-10-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
    ]
