# Generated by Django 5.2.5 on 2025-09-06 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField()),
                ('age_at_death', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='memorials/')),
                ('biography', models.TextField(help_text='Tell their story, achievements, and impact')),
                ('location_of_death', models.CharField(blank=True, max_length=200)),
                ('burial_location', models.CharField(blank=True, max_length=200)),
                ('cultural_background', models.CharField(blank=True, max_length=100)),
                ('religious_affiliation', models.CharField(blank=True, max_length=100)),
                ('traditional_names', models.CharField(blank=True, help_text='Traditional/clan names', max_length=200)),
                ('funeral_date', models.DateTimeField(blank=True, null=True)),
                ('funeral_venue', models.CharField(blank=True, max_length=300)),
                ('funeral_details', models.TextField(blank=True, help_text='Service details, dress code, etc.')),
                ('is_public', models.BooleanField(default=False, help_text='Can non-group members view?')),
                ('allow_condolences', models.BooleanField(default=True)),
                ('allow_memories', models.BooleanField(default=True)),
                ('allow_photos', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial', to='group.group')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_memorials', to=settings.AUTH_USER_MODEL)),
                ('family_admins', models.ManyToManyField(blank=True, related_name='administered_memorials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuneralUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('schedule', 'Schedule Update'), ('venue', 'Venue Information'), ('logistics', 'Logistics & Transport'), ('contribution', 'Contribution Update'), ('general', 'General Announcement')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='memorial.memorial')),
            ],
            options={
                'ordering': ['-is_pinned', '-is_urgent', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CondolenceMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(blank=True, help_text='For non-users or anonymous', max_length=200)),
                ('author_relationship', models.CharField(blank=True, help_text='Friend, Colleague, Neighbor, etc.', max_length=100)),
                ('message', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True, help_text='Family can moderate')),
                ('language', models.CharField(blank=True, help_text='Language of message', max_length=50)),
                ('includes_prayer', models.BooleanField(default=False)),
                ('includes_blessing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condolences', to='memorial.memorial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('memory', 'Memory/Story'), ('condolence', 'Condolence Message'), ('update', 'Funeral Update'), ('tribute', 'Tribute/Poem'), ('photo', 'Photo Memory'), ('announcement', 'Family Announcement')], default='memory', max_length=20)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide author name')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_family_only', models.BooleanField(default=False, help_text='Only family admins can see')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_posts', to=settings.AUTH_USER_MODEL)),
                ('memorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='memorial.memorial')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='memorial.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='memorial.post')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='memorial_posts/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', to='memorial.postimage'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='memorial.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='memorial.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
