# Generated by Django 5.2.5 on 2025-10-10 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customuser', '0006_profile_date_of_death'),
        ('group', '0002_groupmembership_is_deceased'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='memorials/')),
                ('biography', models.TextField(help_text='Tell their story, achievements, and impact')),
                ('location_of_death', models.CharField(blank=True, max_length=200)),
                ('burial_location', models.CharField(blank=True, max_length=200)),
                ('funeral_date', models.DateTimeField(blank=True, null=True)),
                ('funeral_venue', models.CharField(blank=True, max_length=300)),
                ('funeral_details', models.TextField(blank=True, help_text='Service details, dress code, etc.')),
                ('is_public', models.BooleanField(default=False, help_text='Can non-group members view?')),
                ('allow_condolences', models.BooleanField(default=True)),
                ('allow_memories', models.BooleanField(default=True)),
                ('allow_photos', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associated_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial', to='group.group')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_memorials', to=settings.AUTH_USER_MODEL)),
                ('deceased', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorials', to='customuser.profile')),
                ('family_admins', models.ManyToManyField(blank=True, related_name='administered_memorials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
