# Generated by Django 5.2.5 on 2025-09-08 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorial',
            name='associated_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memorial', to='group.group'),
        ),
    ]
