# Generated by Django 5.2.5 on 2025-09-11 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('memorial', '0002_alter_memorial_associated_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorial',
            name='associated_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial', to='group.group'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorial_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
