# Generated by Django 4.2.1 on 2023-07-31 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
