# Generated by Django 4.2.1 on 2023-08-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0007_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='approved',
        ),
    ]
