# Generated by Django 5.2.5 on 2025-10-05 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='post',
        ),
    ]
