# Generated by Django 5.2.5 on 2025-10-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_remove_poll_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='cultural_background',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='religious_affiliation',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='traditional_names',
        ),
    ]
