# Generated by Django 5.2.5 on 2025-10-06 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_profile_is_active_profile_is_deceased'),
        ('feeds', '0003_remove_memorial_cultural_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='age_at_death',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='full_name',
        ),
        migrations.AddField(
            model_name='memorial',
            name='deceased',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memorials', to='customuser.profile'),
        ),
    ]
