# Generated by Django 5.2.5 on 2025-10-10 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_remove_memorial_age_at_death_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorial',
            name='associated_group',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='deceased',
        ),
        migrations.RemoveField(
            model_name='memorial',
            name='family_admins',
        ),
    ]
