# Generated by Django 5.2.5 on 2025-10-10 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_alter_contributioncampaign_memorial'),
        ('feeds', '0005_remove_memorial_associated_group_and_more'),
        ('memorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='memorial_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_posts', to='memorial.memorial'),
        ),
        migrations.DeleteModel(
            name='Memorial',
        ),
    ]
