# Generated by Django 4.0.1 on 2023-10-24 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0003_remove_group_deceased'),
        ('user', '0003_profile_deceased'),
        ('condolence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.AddField(
            model_name='contribution',
            name='member',
            field=models.ManyToManyField(related_name='member_contributions', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='deceased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deceased_contributions', to='chema.group'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_contributions', to='chema.group'),
        ),
        migrations.DeleteModel(
            name='Deceased',
        ),
    ]
