# Generated by Django 4.0.1 on 2023-10-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_deceased'),
        ('condolence', '0003_rename_deceased_contribution_deceased_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='member',
            new_name='deceased_member',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='deceased_group',
        ),
        migrations.AddField(
            model_name='contribution',
            name='contributing_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deceased_contributions', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
