# Generated by Django 4.0.1 on 2023-10-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_deceased'),
        ('condolence', '0007_alter_contribution_group_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='group_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_contributions', to='user.profile'),
        ),
    ]
