# Generated by Django 4.0.1 on 2023-10-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_deceased'),
        ('condolence', '0008_alter_contribution_group_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='deceased_member',
            field=models.ManyToManyField(related_name='member_deceased', to='user.Profile'),
        ),
    ]
