# Generated by Django 4.0.1 on 2023-10-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0003_remove_group_deceased'),
        ('condolence', '0004_rename_member_contribution_deceased_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='group_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='chema.group'),
        ),
    ]
