# Generated by Django 4.2.1 on 2023-08-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
