# Generated by Django 4.0.1 on 2023-10-05 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contribution_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed')], max_length=20, null=True)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condolence.deceased')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chema.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
