# Generated by Django 4.0.1 on 2023-11-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_deceased'),
        ('chema', '0004_alter_dependent_group_alter_dependent_name'),
        ('condolence', '0009_alter_contribution_deceased_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='deceased_member',
        ),
        migrations.CreateModel(
            name='Deceased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('deceased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_deceased', to='user.profile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chema.group')),
            ],
        ),
        migrations.AddField(
            model_name='contribution',
            name='deceased_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_deceased', to='condolence.deceased'),
        ),
    ]
