# Generated by Django 4.0.1 on 2023-11-15 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_deceased'),
        ('condolence', '0011_deceased_group_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='deceased',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deceased', to='user.profile'),
        ),
    ]
