# Generated by Django 4.0.1 on 2023-11-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condolence', '0014_rename_contributions_deceased_contributions_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='deceased',
            name='cont_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
