# Generated by Django 4.0.1 on 2023-11-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_address'),
        ('condolence', '0015_deceased_cont_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deceased',
            name='deceased',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_deceased', to='user.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='contribution',
            unique_together={('deceased_member', 'contributing_member')},
        ),
    ]
