# Generated by Django 4.2.1 on 2023-08-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0003_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
