# Generated by Django 4.2.1 on 2023-08-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chema', '0004_group_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
