# Generated by Django 4.2.1 on 2023-08-08 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chema', '0009_post_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='user',
        ),
        migrations.AddField(
            model_name='dependent',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependent',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
