# Generated by Django 4.0.1 on 2023-10-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deceased',
            field=models.BooleanField(default=False),
        ),
    ]
