# Generated by Django 4.0.1 on 2023-10-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='deceased',
        ),
    ]
