# Generated by Django 5.2.5 on 2025-09-08 07:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('memorial_created', 'Memorial Created'), ('new_memory_posted', 'New Memory Posted'), ('new_condolence', 'New Condolence'), ('condolence_approved', 'Condolence Approved'), ('funeral_update', 'Funeral Update'), ('member_joined', 'New Member Joined'), ('member_approved', 'Member Request Approved'), ('member_left', 'Member Left Group'), ('group_updated', 'Group Information Updated'), ('invitation_received', 'Group Invitation'), ('new_contribution', 'New Contribution Received'), ('contribution_milestone', 'Contribution Milestone'), ('expense_recorded', 'New Expense Recorded'), ('campaign_update', 'Campaign Update'), ('contribution_completed', 'Your Contribution Completed'), ('deadline_approaching', 'Deadline Approaching'), ('welcome', 'Welcome Message'), ('profile_incomplete', 'Complete Your Profile'), ('system_update', 'System Update')], max_length=30, unique=True)),
                ('email_subject_template', models.CharField(blank=True, max_length=200)),
                ('email_body_template', models.TextField(blank=True)),
                ('sms_template', models.CharField(blank=True, max_length=160)),
                ('push_title_template', models.CharField(blank=True, max_length=100)),
                ('push_body_template', models.CharField(blank=True, max_length=200)),
                ('in_app_title_template', models.CharField(max_length=200)),
                ('in_app_message_template', models.TextField()),
                ('available_variables', models.JSONField(default=dict, help_text='JSON object documenting available template variables')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('memorial_created', 'Memorial Created'), ('new_memory_posted', 'New Memory Posted'), ('new_condolence', 'New Condolence'), ('condolence_approved', 'Condolence Approved'), ('funeral_update', 'Funeral Update'), ('member_joined', 'New Member Joined'), ('member_approved', 'Member Request Approved'), ('member_left', 'Member Left Group'), ('group_updated', 'Group Information Updated'), ('invitation_received', 'Group Invitation'), ('new_contribution', 'New Contribution Received'), ('contribution_milestone', 'Contribution Milestone'), ('expense_recorded', 'New Expense Recorded'), ('campaign_update', 'Campaign Update'), ('contribution_completed', 'Your Contribution Completed'), ('deadline_approaching', 'Deadline Approaching'), ('welcome', 'Welcome Message'), ('profile_incomplete', 'Complete Your Profile'), ('system_update', 'System Update')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('action_url', models.URLField(blank=True, max_length=500, null=True)),
                ('group_key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('notification_type', models.CharField(choices=[('memorial_created', 'Memorial Created'), ('new_memory_posted', 'New Memory Posted'), ('new_condolence', 'New Condolence'), ('condolence_approved', 'Condolence Approved'), ('funeral_update', 'Funeral Update'), ('member_joined', 'New Member Joined'), ('member_approved', 'Member Request Approved'), ('member_left', 'Member Left Group'), ('group_updated', 'Group Information Updated'), ('invitation_received', 'Group Invitation'), ('new_contribution', 'New Contribution Received'), ('contribution_milestone', 'Contribution Milestone'), ('expense_recorded', 'New Expense Recorded'), ('campaign_update', 'Campaign Update'), ('contribution_completed', 'Your Contribution Completed'), ('deadline_approaching', 'Deadline Approaching'), ('welcome', 'Welcome Message'), ('profile_incomplete', 'Complete Your Profile'), ('system_update', 'System Update')], max_length=30)),
                ('target_groups', models.JSONField(blank=True, default=list)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('data_template', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notification_batches', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retry', 'Retry')], max_length=20)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='notifications.notification')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorial_created_email', models.BooleanField(default=True)),
                ('memorial_created_push', models.BooleanField(default=True)),
                ('new_memory_posted_email', models.BooleanField(default=True)),
                ('new_memory_posted_push', models.BooleanField(default=True)),
                ('new_condolence_email', models.BooleanField(default=True)),
                ('new_condolence_push', models.BooleanField(default=True)),
                ('funeral_update_email', models.BooleanField(default=True)),
                ('funeral_update_push', models.BooleanField(default=True)),
                ('funeral_update_sms', models.BooleanField(default=False)),
                ('member_joined_email', models.BooleanField(default=True)),
                ('member_joined_push', models.BooleanField(default=True)),
                ('group_invitation_email', models.BooleanField(default=True)),
                ('group_invitation_push', models.BooleanField(default=True)),
                ('group_invitation_sms', models.BooleanField(default=True)),
                ('new_contribution_email', models.BooleanField(default=True)),
                ('new_contribution_push', models.BooleanField(default=True)),
                ('contribution_milestone_email', models.BooleanField(default=True)),
                ('contribution_milestone_push', models.BooleanField(default=True)),
                ('deadline_approaching_email', models.BooleanField(default=True)),
                ('deadline_approaching_push', models.BooleanField(default=True)),
                ('deadline_approaching_sms', models.BooleanField(default=True)),
                ('system_update_email', models.BooleanField(default=False)),
                ('system_update_push', models.BooleanField(default=True)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('push_notifications_enabled', models.BooleanField(default=True)),
                ('sms_notifications_enabled', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(default='22:00')),
                ('quiet_hours_end', models.TimeField(default='07:00')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'delivery_method'], name='notificatio_status_bdbbd2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['group_key'], name='notificatio_group_k_49f5bb_idx'),
        ),
    ]
